version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: keystore-db
    hostname: keystore-db
    environment:
      POSTGRES_USER: keystore
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keystore
    expose:
      - 5432
    volumes:
      - keydata:/var/lib/postgresql/data
    tty: true
    stdin_open: true
    networks:
      - keystore

  webap:
    build: .
    restart: always
    container_name: keystore-webap
    hostname: keystore-webapp
    ports:
      - 8000:80
    tty: true
    stdin_open: true
    networks:
      - keystore

volumes:
  keydata:

networks:
  keystore:
    name: keystore
